export const BASE_URL = 'http://3.138.124.101:9000/';
export const REGISTER = 'register';
export const VERIFYOTP = 'verifyOtp';
export const LOGIN = 'login';
export const USERDETAIL ='addUpdateDetails'
export const ADDRESS ='addUpdateAddress'
export const VERIFYLOGIN ='verifyLogin'
export const GETPROFILE ='getUserInfo'
export const PROFILEUPDATE ='addUpdateDetails'
export const GET_ALL_PROFILE ='getProfile'
export const FACEBOOK_LOGIN ='socialLogin/'
export const GOOGLE_LOGIN ='socialLogin/'