const ImagePath = {
    backgroundImage: require('../assets/bg.png'),
    logo:require('../assets/logo.png'),
    MainLogo:require('../assets/mainlogo.png'),
    logohd:require('../assets/Logohd.png'),
    logoText:require('../assets/logotext.png'),
    logoTextlong:require('../assets/logotextlong.png'),
    versionText:require('../assets/versiontext.png'),
    Applelogo:require('../assets/applelogo.png'),
    Applelogohd:require('../assets/applehd.png'),
    Googlelogo:require('../assets/googlelogo.png'),
    googlehd:require('../assets/googlehd.png'),
    userImage:require('../assets/userprofile.png'),
    camera:require('../assets/camera.png'),
    back:require('../assets/back.png'),
    Search:require('../assets/Search.png'),
    Notification:require('../assets/Notification.png'),
    Profile:require('../assets/profile.png'),
    Chat:require('../assets/chat.png'),
    HomepageLanding:require('../assets/hompagelanding.png'),
    HomePage1:require('../assets/hompage1.png'),
    homePage3:require('../assets/homepage3.png'),
    like:require('../assets/like.png'),
    openFolder:require('../assets/openfolder.png'),
    Hometab:require('../assets/Hometab.png'),
    Chattab:require('../assets/Chattab.png'),
    NotificationTab:require('../assets/Notificationtab.png'),
    ProfileTab:require('../assets/Profiletab.png'),
    menu:require('../assets/menu.png'),
    backReverse:require('../assets/backreverse.png'),
    CheckImage:require('../assets/check.png'),
    Feed:require('../assets/feed.png'),
    Bids:require('../assets/bids.png'),
    Open:require('../assets/open.png'),
    Nopost:require('../assets/nopost.png'),
    Setting:require('../assets/Setting.png'),

  };
  
  export default ImagePath;